;redcode
;name sleepless 1.2
;assert 1

target		DAT	#0,	#0
bomb		DAT	#0,	#0
		;
sleepless	MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		SPL	0,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		MOV	bomb,	<target
		JMP	bomb,	<target
		;
		END	sleepless
