;redcode-nano
;name another evolver...
;author Blake Escritt
; <bescritt@gmail.com>
;assert CORESIZE==80
;Strat- generated by CRE
;Strat- by Loren Jamison
;Strat- http://cre.sourceforge.net/index.htm
SPL.B #68, {53
MOV.I *75, <79
MOV.I @17, {79
MOV.I <17, {79
JMP.I $79, >79
END 0

