;redcode-nano
;name qopt-819271332
;author bvowk
;strategy No humans were involved in the creation of this warrior!
;strategy generated by CSM in python
;assert 1

START	ADD.AB # 75, # 69
	JMZ.F $ -1, @ -1
	MOV.I $ -1, > -2
	DJN.A $ -2, } 46

