;redcode-nano
;name qopt-3193069885
;author bvowk
;strategy No humans were involved in the creation of this warrior!
;strategy generated by CSM in python
;assert 1

START   ADD.AB # 58, # 4
        JMZ.A $ -1, > -1
        SPL.A # 22, * 41
        MOV.I { -2, < -3
        DJN.A $ -1, } 77

