;redcode
;name Validate 1.1R
;author Stefan Strack
;assert 1

START  SPL    $     8, $     3     
       JMZ    <    -1, $     0     
       DJN    $     0, #    36     
       SUB    #     1, @    -3     
       MOV    $     2, <    87     
       JMP    $    -1, $     0     
       DAT    #     0, #     1     
       DAT    #     0, #     3     
       SPL    $     2, $     0     
       DAT    <    -2, <    -2     
       CMP    $    -4, $    -3     
       JMP    $    73, $     0     
       SPL    $     5, $     0     
       JMZ    $     3, <     0     
       DAT    #     0, #     1     
       DAT    #     0, #     2     
       JMP    @     0, <     0     
       JMP    <     2, #     0     
       JMP    $     3, $     0     
       DAT    #     0, #     0     
       DAT    #     0, #    -1     
       CMP    $    -7, $    -6     
       JMP    $    62, $     0     
       CMP    $    -4, $    -3     
       JMP    $    60, $     0     
       JMP    <     2, <     2     
       JMP    $     3, $     0     
       DAT    #     0, #     0     
       DAT    #     0, #    -2     
       CMP    $    -2, $    -1     
       JMP    $    54, $     0     
       MOV    $     1, <     1     
       JMN    $     2, $     1     
       JMN    $     2, $     1     
       CMP    $    -2, $    -1     
       JMP    $    49, $     0     
       MOV    @     0, <     1     
       JMN    $     2, $     1     
       JMN    $     2, $     1     
       CMP    $    -2, $    -1     
       JMP    $    44, $     0     
       SPL    $     5, $     0     
       MOV    <     1, $     2     
       DAT    <     0, #     1     
       DAT    <     0, #     1     
       DAT    <     0, #    -1     
       MOV    <     1, $     1     
       JMZ    $     2, $     1     
       JMP    $    36, $     0     
       CMP    $    -6, $    -4     
       JMP    $    34, $     0     
       ADD    $     1, <     1     
       JMP    $     1, $     1     
       JMP    $     2, $     1     
       CMP    $    -2, $    -1     
       JMP    $    29, $     0     
       ADD    @     0, <     1     
       JMP    $     1, $     1     
       JMP    $    26, $     0     
       CMP    $    -6, $    -2     
       JMP    $    24, $     0     
       SPL    $     4, $     0     
       CMP    $     4, $     5     
       JMP    $     5, $     0     
       JMP    $    20, $     0     
       SUB    <     1, $     1     
       DAT    #     2, #     1     
       DAT    #     0, #     0     
       CMP    $    -2, $    -1     
       JMP    $    15, $     0     
       SUB    <     1, <     1     
       JMP    $     3, $     1     
       SUB    <    -2, <     1     
       JMP    $     3, $    -1     
       CMP    $    -4, $    -2     
       JMP    $     9, $     0     
       CMP    $    -5, $    -3     
       JMP    $     7, $     0     
       CMP    $   -79, $     3     
       JMP    $     3, $     0     
       JMP    $     4, $     0     
       DAT    #     0, #     0     
       SLT    #     0, $   -80     
       JMP    $     5, $     0     
       MOV    $   -82, $     3     
       MOV    $   -79, $   -83     
       JMP    $   -82, $     0     
       DAT    #     0, #     0     
       MOV    $    -1, $   -84     
       JMP    $     0, $     0     

       END      START
